import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import "./swiper.css";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/effect-coverflow';
import "swiper/css/mousewheel";


import PrelineScriptWrapper from "./components/PrelineScriptWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const obitron = Orbitron({
  variable: "--font-obitron",
  subsets: ["latin"],
  weight: ["400","700"],
});
 
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio - Thet Wai Hnin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#050E7F] w-full min-h-dvh overflow-x-hidden
           ${geistSans.variable} ${geistMono.variable} antialiased
           ${obitron.variable}
           `}
      >
        {children}
      </body>
            <PrelineScriptWrapper />

    </html>
  );
}
